users_auth/basicapp/urls.py
from django.urls import path
from . import views

# template urls
app_name  = 'basicapp'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

users_auth/users_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('',views.indexx,name='indexx'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/', views.special, name='special'),

]

users_auth/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

users_auth/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

users_auth/basicapp/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm



from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout



# Create your views here.
def indexx(request):
    return render(request,'basicapp/indexx.html')

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # checking if user actually provided the profile picture
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm()

    return render(request,'basicapp/registration.html',{'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('indexx'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'basicapp/login.html',{})

@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('indexx'))

@login_required()
def special(request):
    return HttpResponse("You are logged in, NICE!!")

users_auth/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .jumbotron {
          padding: 2rem 1rem;
          margin-bottom: 2rem;
          background-color: #e9ecef;
          border-radius: .3rem;
}</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'indexx' %}">DJANGO</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'basicapp:register' %}">Registration</a>
        </li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a> </li>
          {% endif %}

      </ul>
    </div>
  </div>
</nav><br>
<div class="container">
    {% block body_block %}
<!--    anything outside of this will be inherited if you extend-->

    {% endblock %}
</div>

</body>
</html>

users_auth/templates/basicapp/indexx.html
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>
{% endblock %}

users_auth/templates/basicapp/login.html
{% extends "basicapp/base.html" %}
{% block body_block %}
<div class = "jumbotron">
    <h1>Please Login!! </h1>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>

</div>
{% endblock %}

users_auth/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thankyou for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form :</h3>

        <form method="post" enctype="multipart/form-data" >
            {% csrf_token%}

            <!-- user_from and profile_form are defined within the context dictionary of the views -->

            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">

        </form>
    {% endif %}
</div>

{% endblock %}